### ISSUE TITLE
"Field names cannot contain a ." when trying to create a new container token (PF2E)

### ISSUE THREAD

**Issue by VeilOfOblivion** [kamcknig/pick-up-stix#168]
**Describe the bug**
Can't drop an item of the container type on the scene and choose container. Results in error "Field names cannot contain a ." (PF2E)

**To Reproduce**
1. Import e.g. a Backpack from the equipment compendium (an item of type container)
2. Drop it in the scene
3. Choose "Container'
4. See the error message
5. See that no token is created

**Expected behavior**
A container token should be created

**Screenshots**

**Foundry Version**
0.7.7 (PF2E: 1.10.17.2355)

**Pick-Up-Stix Version**
0.13.5

**Details**
- No other modules are active when this happens.
- Stack Trace:
foundry.js:3780 Error: Field names cannot contain a .
    at checkKey (C:\Program Files\FoundryVTT\resources\app\node_modules\nedb\lib\model.js:36:11)
    at C:\Program Files\FoundryVTT\resources\app\node_modules\nedb\lib\model.js:54:7
    at Array.forEach (<anonymous>)
    at checkObject (C:\Program Files\FoundryVTT\resources\app\node_modules\nedb\lib\model.js:53:22)
    at C:\Program Files\FoundryVTT\resources\app\node_modules\nedb\lib\model.js:55:7
    at Array.forEach (<anonymous>)
    at checkObject (C:\Program Files\FoundryVTT\resources\app\node_modules\nedb\lib\model.js:53:22)
    at C:\Program Files\FoundryVTT\resources\app\node_modules\nedb\lib\model.js:48:7
    at Array.forEach (<anonymous>)
    at checkObject (C:\Program Files\FoundryVTT\resources\app\node_modules\nedb\lib\model.js:47:9)
_handleError @ foundry.js:3780
(anonymous) @ foundry.js:3761
n.onack @ index.js:83
n.onpacket @ index.js:83
(anonymous) @ index.js:83
n.emit @ index.js:83
n.ondecoded @ index.js:83
(anonymous) @ index.js:83
n.emit @ index.js:83
a.add @ index.js:83
n.ondata @ index.js:83
(anonymous) @ index.js:83
n.emit @ index.js:83
n.onPacket @ index.js:83
(anonymous) @ index.js:83
n.emit @ index.js:83
n.onPacket @ index.js:83
n.onData @ index.js:83
ws.onmessage @ index.js:83
foundry.js:3777 Uncaught (in promise) Error: Field names cannot contain a .
    at checkKey (C:\Program Files\FoundryVTT\resources\app\node_modules\nedb\lib\model.js:36:11)
    at C:\Program Files\FoundryVTT\resources\app\node_modules\nedb\lib\model.js:54:7
    at Array.forEach (<anonymous>)
    at checkObject (C:\Program Files\FoundryVTT\resources\app\node_modules\nedb\lib\model.js:53:22)
    at C:\Program Files\FoundryVTT\resources\app\node_modules\nedb\lib\model.js:55:7
    at Array.forEach (<anonymous>)
    at checkObject (C:\Program Files\FoundryVTT\resources\app\node_modules\nedb\lib\model.js:53:22)
    at C:\Program Files\FoundryVTT\resources\app\node_modules\nedb\lib\model.js:48:7
    at Array.forEach (<anonymous>)
    at checkObject (C:\Program Files\FoundryVTT\resources\app\node_modules\nedb\lib\model.js:47:9)

- Visually, everything works fine if I create a new container from scratch. But then I still get an error in the console:
main.bundle.js:1 Uncaught (in promise) TypeError: Cannot read property 'data' of null
    at Function.renderEffects (main.bundle.js:1)
    at Function._hookOnCreateToken (main.bundle.js:1)
    at main.bundle.js:1
    at Function._call (foundry.js:2496)
    at Function.callAll (foundry.js:2456)
    at Function._handleCreateEmbeddedEntity (foundry.js:29823)
    at Function._handleCreateEmbeddedEntity (foundry.js:34191)
    at Scene.createEmbeddedEntity (foundry.js:29794)
    at async Function.create (foundry.js:11416)
    at async createToken (main.ts:764). 

Let me know if you need further information.

**Comment by kamcknig** [comment]
@VeilOfOblivion I have seen this randomly as well, and for me it doesn't happen every single time, it seems random (in D&D 5 that is). I did try your steps and it gave the error in PF2E and does seem to do it every time. The weird thing is, the name doesn't have a "." so i'm not sure what's going on but I will be looking into it

**Comment by kamcknig** [comment]
@VeilOfOblivion , found the issue and should be fixed in version 0.13.7, thank you!
